version: 2.1
orbs:
  scribe: scribe-security/orbs@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    environment:
      ENV: dev
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - scribe/install
      - scribe/bom:
          target: alpine:latest

  bom-e2e-tests:
    docker:
      - image: cimg/base:2021.04
    environment:
      SCRIBE_URL: https://airflow.staging.scribesecurity.com
      SCRIBE_LOGIN_URL: "https://scribe-hub-staging.us.auth0.com"
      SCRIBE_AUDIENCE: "api.staging.scribesecurity.com"
      ENV: dev
    steps:
      - run:
          name: custom checkout
          command: |
            git clone -b v1.0.0-alpha.4 --single-branch https://github.com/mongo-express/mongo-express.git --depth=1 mongo-express-scm
      - scribe/install
      - scribe/bom:
          target: dir:mongo-express-scm
          verbose: 2
          scribe-enable: true
          product-key: circle.orbs.deploy.bom
          scribe-client-id: $SCRIBE_STAGING_M2M_CLIENT_ID
          scribe-client-secret: $SCRIBE_STAGING_M2M_CLIENT_SECRET
          scribe-url:  $SCRIBE_URL
          scribe-login-url: $SCRIBE_LOGIN_URL
          scribe-auth-audience: $SCRIBE_AUDIENCE
      - scribe/bom:
          target: git:mongo-express-scm
          verbose: 2
          scribe-enable: true
          product-key: circle.orbs.deploy.bom
          scribe-client-id: $SCRIBE_STAGING_M2M_CLIENT_ID
          scribe-client-secret: $SCRIBE_STAGING_M2M_CLIENT_SECRET
          scribe-url:  $SCRIBE_URL
          scribe-login-url: $SCRIBE_LOGIN_URL
          scribe-auth-audience: $SCRIBE_AUDIENCE
      - scribe/bom:
          target: mongo-express:1.0.0-alpha.4
          verbose: 2
          scribe-enable: true
          product-key: circle.orbs.deploy.bom
          scribe-client-id: $SCRIBE_STAGING_M2M_CLIENT_ID
          scribe-client-secret: $SCRIBE_STAGING_M2M_CLIENT_SECRET
          scribe-url:  $SCRIBE_URL
          scribe-login-url: $SCRIBE_LOGIN_URL
          scribe-auth-audience: $SCRIBE_AUDIENCE

  policy-e2e-tests:
    docker:
      - image: cimg/base:2021.04
    environment:
      SCRIBE_URL: "https://api.staging.scribesecurity.com"
      SCRIBE_LOGIN_URL: "https://scribesecurity-staging.us.auth0.com"
      SCRIBE_AUDIENCE: "api.staging.scribesecurity.com"
      ENV: dev
    steps:
      - scribe/install
      - scribe/bom:
          target: busybox:latest
          verbose: 2
          scribe-enable: true
          product-key: circle.orbs.deploy.policy
          format: statement
          scribe-client-id: $SCRIBE_STAGING_M2M_CLIENT_ID
          scribe-client-secret: $SCRIBE_STAGING_M2M_CLIENT_SECRET
          scribe-url:  $SCRIBE_URL
          scribe-login-url: $SCRIBE_LOGIN_URL
          scribe-auth-audience: $SCRIBE_AUDIENCE
      - scribe/verify:
          target: busybox:latest
          verbose: 2
          product-key: circle.orbs.deploy.policy
          input-format: statement
          scribe-enable: true
          scribe-client-id: $SCRIBE_STAGING_M2M_CLIENT_ID
          scribe-client-secret: $SCRIBE_STAGING_M2M_CLIENT_SECRET
          scribe-url:  $SCRIBE_URL
          scribe-login-url: $SCRIBE_LOGIN_URL
          scribe-auth-audience: $SCRIBE_AUDIENCE

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - bom-e2e-tests:
          filters: *filters
          context: scribe-staging
      - policy-e2e-tests:
          filters: *filters
          context: scribe-staging
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: scribe-security/orbs
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - bom-e2e-tests
            - policy-e2e-tests
          context: orb-publishing
          circleci-token: CIRCLE_TOKEN3
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

