version: 2.1
orbs:
  gensbom: scribe-security/gensbom@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - gensbom/install
      - gensbom/bom:
          target: alpine:latest

  integration-tests:
    docker:
      - image: ubuntu:latest
    environment:
      SCRIBE_URL: "https://api.staging.scribesecurity.com"
      SCRIBE_LOGIN_URL: "https://scribesecurity-staging.us.auth0.com"
      SCRIBE_AUDIENCE: "api.staging.scribesecurity.com"
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - gensbom/install
      - gensbom/bom:
          target: alpine:latest

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - integration-tests:
          filters: *filters
          context: scribe-staging
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: scribe-security/gensbom-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - integration-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
