description: >
  * Create SBOM for image built by local Docker `image_name:latest` image.

usage:
  version: 2.1
  orbs:
    scribe: scribe-security/orbs@x.y.z

jobs:
  local-image-job:
    docker:
      - image: docker:stable-git
    steps:
      - checkout

      # Install scribe tool
      - scribe/install

      - setup_remote_docker:
          docker_layer_caching: true

      # Docker build ..

      - scribe/bom:
          target: image_name:latest
          output-file: my_sbom.json
          force: true

      # Storing as artifacts
      - store_artifacts:
          path: scribe/
          destination: scribe-evidence

workflows:
  example-local-image-workflow:
    jobs:
      - local-image-job
