description: >
  * Generate SLSA Provenance for `mongo-express` remote git repository.
  * Generate SLSA Provenance for checked out local git repository.

usage:
  version: 2.1
  orbs:
    scribe: scribe-security/orbs@x.y.z

jobs:
  scribe-git-target-job:
    docker:
      - image: docker:stable-git
    steps:
      - checkout

      # Install scribe tool
      - scribe/install

      # Create SBOM for `mongo-express` remote git repository.
      - scribe/bom:
          target: git:https://github.com/mongo-express/mongo-express.git
          force: true

      # Create SBOM for checked out local git repository.
      - scribe/bom:
          target: git:.
          force: true

workflows:
  example-scribe-git-target-workflow:
    jobs:
      - scribe-git-target-job
